python AddressableLEDsConverterForMQTTESP32.py -f "150LED_XTMAS.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "150LED_FIREFLIES.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "150LED_SPARKLE.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "150LED_BLUE_REFLEX.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "150LED_CRAZY_WHITES.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "150LED_RAINBOW_ROTATE.leds"

python AddressableLEDsConverterForMQTTESP32.py -f "100LED_BLUE_REFLEX.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "100LED_RAINBOW_ROTATE.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "100LED_XTMAS.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "100LED_SPARKLE.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "100LED_CANDLE_SHUTTLE.leds"

python AddressableLEDsConverterForMQTTESP32.py -f "50LED_METEO.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "50LED_RGB_ROTATE.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "50LED_RAINBOW_ROTATE.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "50LED_RED_BLUE_UP_DOWN.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "50LED_FALLING_STARS.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "50LED_FIREWORKS.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "50LED_WAVES.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "50LED_XTMAS.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "50LED_FIREFLIES.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "50LED_RGB_UP_DOWN.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "50LED_SPARKLE.leds"
python AddressableLEDsConverterForMQTTESP32.py -f "50LED_RANDOM_BLINK.leds"
